<?php

/**
 * BasePost
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $blog_id
 * @property integer $web_user_id
 * @property clob $text
 * @property integer $create_time
 * @property WebUser $WebUser
 * @property Blog $Blog
 * @property Doctrine_Collection $comments
 * 
 * @method integer             getId()          Returns the current record's "id" value
 * @method integer             getBlogId()      Returns the current record's "blog_id" value
 * @method integer             getWebUserId()   Returns the current record's "web_user_id" value
 * @method clob                getText()        Returns the current record's "text" value
 * @method integer             getCreateTime()  Returns the current record's "create_time" value
 * @method WebUser             getWebUser()     Returns the current record's "WebUser" value
 * @method Blog                getBlog()        Returns the current record's "Blog" value
 * @method Doctrine_Collection getComments()    Returns the current record's "comments" collection
 * @method Post                setId()          Sets the current record's "id" value
 * @method Post                setBlogId()      Sets the current record's "blog_id" value
 * @method Post                setWebUserId()   Sets the current record's "web_user_id" value
 * @method Post                setText()        Sets the current record's "text" value
 * @method Post                setCreateTime()  Sets the current record's "create_time" value
 * @method Post                setWebUser()     Sets the current record's "WebUser" value
 * @method Post                setBlog()        Sets the current record's "Blog" value
 * @method Post                setComments()    Sets the current record's "comments" collection
 * 
 * @package    sf
 * @subpackage model
 * @author     VozdvIN
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePost extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('posts');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('blog_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('web_user_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('text', 'clob', null, array(
             'type' => 'clob',
             'notnull' => true,
             ));
        $this->hasColumn('create_time', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('WebUser', array(
             'local' => 'web_user_id',
             'foreign' => 'id',
             'onDelete' => 'SET NULL'));

        $this->hasOne('Blog', array(
             'local' => 'blog_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasMany('Comment as comments', array(
             'local' => 'id',
             'foreign' => 'post_id'));
    }
}