<?php

/**
 * BaseTip
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $task_id
 * @property string $name
 * @property clob $define
 * @property integer $delay
 * @property integer $answer_id
 * @property Task $Task
 * @property Answer $Answer
 * @property Doctrine_Collection $UsedTip
 * 
 * @method integer             getId()        Returns the current record's "id" value
 * @method integer             getTaskId()    Returns the current record's "task_id" value
 * @method string              getName()      Returns the current record's "name" value
 * @method clob                getDefine()    Returns the current record's "define" value
 * @method integer             getDelay()     Returns the current record's "delay" value
 * @method integer             getAnswerId()  Returns the current record's "answer_id" value
 * @method Task                getTask()      Returns the current record's "Task" value
 * @method Answer              getAnswer()    Returns the current record's "Answer" value
 * @method Doctrine_Collection getUsedTip()   Returns the current record's "UsedTip" collection
 * @method Tip                 setId()        Sets the current record's "id" value
 * @method Tip                 setTaskId()    Sets the current record's "task_id" value
 * @method Tip                 setName()      Sets the current record's "name" value
 * @method Tip                 setDefine()    Sets the current record's "define" value
 * @method Tip                 setDelay()     Sets the current record's "delay" value
 * @method Tip                 setAnswerId()  Sets the current record's "answer_id" value
 * @method Tip                 setTask()      Sets the current record's "Task" value
 * @method Tip                 setAnswer()    Sets the current record's "Answer" value
 * @method Tip                 setUsedTip()   Sets the current record's "UsedTip" collection
 * 
 * @package    sf
 * @subpackage model
 * @author     VozdvIN
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTip extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('tips');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('task_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('name', 'string', 64, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 64,
             ));
        $this->hasColumn('define', 'clob', null, array(
             'type' => 'clob',
             'notnull' => true,
             ));
        $this->hasColumn('delay', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => 0,
             ));
        $this->hasColumn('answer_id', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Task', array(
             'local' => 'task_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Answer', array(
             'local' => 'answer_id',
             'foreign' => 'id',
             'onDelete' => 'SET NULL'));

        $this->hasMany('UsedTip', array(
             'local' => 'id',
             'foreign' => 'tip_id'));
    }
}