<?php

/**
 * BaseGameCandidate
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $team_id
 * @property integer $game_id
 * @property Team $Team
 * @property Game $Game
 * 
 * @method integer       getId()      Returns the current record's "id" value
 * @method integer       getTeamId()  Returns the current record's "team_id" value
 * @method integer       getGameId()  Returns the current record's "game_id" value
 * @method Team          getTeam()    Returns the current record's "Team" value
 * @method Game          getGame()    Returns the current record's "Game" value
 * @method GameCandidate setId()      Sets the current record's "id" value
 * @method GameCandidate setTeamId()  Sets the current record's "team_id" value
 * @method GameCandidate setGameId()  Sets the current record's "game_id" value
 * @method GameCandidate setTeam()    Sets the current record's "Team" value
 * @method GameCandidate setGame()    Sets the current record's "Game" value
 * 
 * @package    sf
 * @subpackage model
 * @author     VozdvIN
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseGameCandidate extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('game_candidates');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('team_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('game_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));


        $this->index('ui_team_game', array(
             'type' => 'unique',
             'fields' => 
             array(
              0 => 'team_id',
              1 => 'game_id',
             ),
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Team', array(
             'local' => 'team_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Game', array(
             'local' => 'game_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}