<?php

/**
 * BaseTeamCandidate
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $web_user_id
 * @property integer $team_id
 * @property WebUser $WebUser
 * @property Team $Team
 * 
 * @method integer       getId()          Returns the current record's "id" value
 * @method integer       getWebUserId()   Returns the current record's "web_user_id" value
 * @method integer       getTeamId()      Returns the current record's "team_id" value
 * @method WebUser       getWebUser()     Returns the current record's "WebUser" value
 * @method Team          getTeam()        Returns the current record's "Team" value
 * @method TeamCandidate setId()          Sets the current record's "id" value
 * @method TeamCandidate setWebUserId()   Sets the current record's "web_user_id" value
 * @method TeamCandidate setTeamId()      Sets the current record's "team_id" value
 * @method TeamCandidate setWebUser()     Sets the current record's "WebUser" value
 * @method TeamCandidate setTeam()        Sets the current record's "Team" value
 * 
 * @package    sf
 * @subpackage model
 * @author     VozdvIN
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTeamCandidate extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('team_candidates');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('web_user_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('team_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => 0,
             ));


        $this->index('ui_webuser_team', array(
             'type' => 'unique',
             'fields' => 
             array(
              0 => 'web_user_id',
              1 => 'team_id',
             ),
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('WebUser', array(
             'local' => 'web_user_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Team', array(
             'local' => 'team_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}