<?php

/**
 * BaseTeam
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property string $full_name
 * @property Doctrine_Collection $games
 * @property Doctrine_Collection $gameCandidates
 * @property Doctrine_Collection $gameCreateRequests
 * @property Doctrine_Collection $teamCandidates
 * @property Doctrine_Collection $teamPlayers
 * @property Doctrine_Collection $teamStates
 * 
 * @method integer             getId()                 Returns the current record's "id" value
 * @method string              getName()               Returns the current record's "name" value
 * @method string              getFullName()           Returns the current record's "full_name" value
 * @method Doctrine_Collection getGames()              Returns the current record's "games" collection
 * @method Doctrine_Collection getGameCandidates()     Returns the current record's "gameCandidates" collection
 * @method Doctrine_Collection getGameCreateRequests() Returns the current record's "gameCreateRequests" collection
 * @method Doctrine_Collection getTeamCandidates()     Returns the current record's "teamCandidates" collection
 * @method Doctrine_Collection getTeamPlayers()        Returns the current record's "teamPlayers" collection
 * @method Doctrine_Collection getTeamStates()         Returns the current record's "teamStates" collection
 * @method Team                setId()                 Sets the current record's "id" value
 * @method Team                setName()               Sets the current record's "name" value
 * @method Team                setFullName()           Sets the current record's "full_name" value
 * @method Team                setGames()              Sets the current record's "games" collection
 * @method Team                setGameCandidates()     Sets the current record's "gameCandidates" collection
 * @method Team                setGameCreateRequests() Sets the current record's "gameCreateRequests" collection
 * @method Team                setTeamCandidates()     Sets the current record's "teamCandidates" collection
 * @method Team                setTeamPlayers()        Sets the current record's "teamPlayers" collection
 * @method Team                setTeamStates()         Sets the current record's "teamStates" collection
 * 
 * @package    sf
 * @subpackage model
 * @author     VozdvIN
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTeam extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('teams');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('name', 'string', 32, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 32,
             ));
        $this->hasColumn('full_name', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Game as games', array(
             'local' => 'id',
             'foreign' => 'team_id'));

        $this->hasMany('GameCandidate as gameCandidates', array(
             'local' => 'id',
             'foreign' => 'team_id'));

        $this->hasMany('GameCreateRequest as gameCreateRequests', array(
             'local' => 'id',
             'foreign' => 'team_id'));

        $this->hasMany('TeamCandidate as teamCandidates', array(
             'local' => 'id',
             'foreign' => 'team_id'));

        $this->hasMany('TeamPlayer as teamPlayers', array(
             'local' => 'id',
             'foreign' => 'team_id'));

        $this->hasMany('TeamState as teamStates', array(
             'local' => 'id',
             'foreign' => 'team_id'));
    }
}