<?php

/**
 * BasePostedAnswer
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $task_state_id
 * @property string $value
 * @property integer $post_time
 * @property integer $web_user_id
 * @property integer $answer_id
 * @property integer $status
 * @property TaskState $TaskState
 * @property Answer $Answer
 * @property WebUser $WebUser
 * 
 * @method integer      getId()            Returns the current record's "id" value
 * @method integer      getTaskStateId()   Returns the current record's "task_state_id" value
 * @method string       getValue()         Returns the current record's "value" value
 * @method integer      getPostTime()      Returns the current record's "post_time" value
 * @method integer      getWebUserId()     Returns the current record's "web_user_id" value
 * @method integer      getAnswerId()      Returns the current record's "answer_id" value
 * @method integer      getStatus()        Returns the current record's "status" value
 * @method TaskState    getTaskState()     Returns the current record's "TaskState" value
 * @method Answer       getAnswer()        Returns the current record's "Answer" value
 * @method WebUser      getWebUser()       Returns the current record's "WebUser" value
 * @method PostedAnswer setId()            Sets the current record's "id" value
 * @method PostedAnswer setTaskStateId()   Sets the current record's "task_state_id" value
 * @method PostedAnswer setValue()         Sets the current record's "value" value
 * @method PostedAnswer setPostTime()      Sets the current record's "post_time" value
 * @method PostedAnswer setWebUserId()     Sets the current record's "web_user_id" value
 * @method PostedAnswer setAnswerId()      Sets the current record's "answer_id" value
 * @method PostedAnswer setStatus()        Sets the current record's "status" value
 * @method PostedAnswer setTaskState()     Sets the current record's "TaskState" value
 * @method PostedAnswer setAnswer()        Sets the current record's "Answer" value
 * @method PostedAnswer setWebUser()       Sets the current record's "WebUser" value
 * 
 * @package    sf
 * @subpackage model
 * @author     VozdvIN
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePostedAnswer extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('posted_answers');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('task_state_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('value', 'string', 64, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 64,
             ));
        $this->hasColumn('post_time', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('web_user_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('answer_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('status', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => 0,
             ));


        $this->index('ui_state_value', array(
             'type' => 'unique',
             'fields' => 
             array(
              0 => 'task_state_id',
              1 => 'value',
             ),
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('TaskState', array(
             'local' => 'task_state_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Answer', array(
             'local' => 'answer_id',
             'foreign' => 'id',
             'onDelete' => 'SET NULL'));

        $this->hasOne('WebUser', array(
             'local' => 'web_user_id',
             'foreign' => 'id',
             'onDelete' => 'SET NULL'));
    }
}