<?php

/**
 * BaseGameCreateRequest
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $team_id
 * @property string $name
 * @property string $description
 * @property string $tag
 * @property Team $Team
 * 
 * @method integer           getId()          Returns the current record's "id" value
 * @method integer           getTeamId()      Returns the current record's "team_id" value
 * @method string            getName()        Returns the current record's "name" value
 * @method string            getDescription() Returns the current record's "description" value
 * @method string            getTag()         Returns the current record's "tag" value
 * @method Team              getTeam()        Returns the current record's "Team" value
 * @method GameCreateRequest setId()          Sets the current record's "id" value
 * @method GameCreateRequest setTeamId()      Sets the current record's "team_id" value
 * @method GameCreateRequest setName()        Sets the current record's "name" value
 * @method GameCreateRequest setDescription() Sets the current record's "description" value
 * @method GameCreateRequest setTag()         Sets the current record's "tag" value
 * @method GameCreateRequest setTeam()        Sets the current record's "Team" value
 * 
 * @package    sf
 * @subpackage model
 * @author     VozdvIN
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseGameCreateRequest extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('game_create_requests');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('team_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('description', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('tag', 'string', 32, array(
             'type' => 'string',
             'length' => 32,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Team', array(
             'local' => 'team_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}