<?php

/**
 * BaseSystemSettings
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $notify_email_addr
 * @property string $contact_email_addr
 * 
 * @method integer        getId()                 Returns the current record's "id" value
 * @method string         getNotifyEmailAddr()    Returns the current record's "notify_email_addr" value
 * @method string         getContactEmailAddr()   Returns the current record's "contact_email_addr" value
 * @method SystemSettings setId()                 Sets the current record's "id" value
 * @method SystemSettings setNotifyEmailAddr()    Sets the current record's "notify_email_addr" value
 * @method SystemSettings setContactEmailAddr()   Sets the current record's "contact_email_addr" value
 * 
 * @package    sf
 * @subpackage model
 * @author     VozdvIN
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSystemSettings extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('system_settings');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('notify_email_addr', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'default' => 'do_not_reply@null.no',
             'length' => 255,
             ));
        $this->hasColumn('contact_email_addr', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'default' => 'nowhere@null.no',
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}