<?php

/**
 * BaseGrantedPermission
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $web_user_id
 * @property integer $permission_id
 * @property integer $filter_id
 * @property boolean $deny
 * @property WebUser $WebUser
 * @property Permission $Permission
 * 
 * @method integer           getId()            Returns the current record's "id" value
 * @method integer           getWebUserId()     Returns the current record's "web_user_id" value
 * @method integer           getPermissionId()  Returns the current record's "permission_id" value
 * @method integer           getFilterId()      Returns the current record's "filter_id" value
 * @method boolean           getDeny()          Returns the current record's "deny" value
 * @method WebUser           getWebUser()       Returns the current record's "WebUser" value
 * @method Permission        getPermission()    Returns the current record's "Permission" value
 * @method GrantedPermission setId()            Sets the current record's "id" value
 * @method GrantedPermission setWebUserId()     Sets the current record's "web_user_id" value
 * @method GrantedPermission setPermissionId()  Sets the current record's "permission_id" value
 * @method GrantedPermission setFilterId()      Sets the current record's "filter_id" value
 * @method GrantedPermission setDeny()          Sets the current record's "deny" value
 * @method GrantedPermission setWebUser()       Sets the current record's "WebUser" value
 * @method GrantedPermission setPermission()    Sets the current record's "Permission" value
 * 
 * @package    sf
 * @subpackage model
 * @author     VozdvIN
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseGrantedPermission extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('granted_permissions');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('web_user_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('permission_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => 0,
             ));
        $this->hasColumn('filter_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => 0,
             ));
        $this->hasColumn('deny', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => false,
             ));


        $this->index('ui_webuser_permission_filter', array(
             'type' => 'unique',
             'fields' => 
             array(
              0 => 'web_user_id',
              1 => 'permission_id',
              2 => 'filter_id',
             ),
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('WebUser', array(
             'local' => 'web_user_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Permission', array(
             'local' => 'permission_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}