<?php

/**
 * BaseUsedTip
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $task_state_id
 * @property integer $tip_id
 * @property integer $status
 * @property integer $used_since
 * @property TaskState $TaskState
 * @property Tip $Tip
 * 
 * @method integer   getId()            Returns the current record's "id" value
 * @method integer   getTaskStateId()   Returns the current record's "task_state_id" value
 * @method integer   getTipId()         Returns the current record's "tip_id" value
 * @method integer   getStatus()        Returns the current record's "status" value
 * @method integer   getUsedSince()     Returns the current record's "used_since" value
 * @method TaskState getTaskState()     Returns the current record's "TaskState" value
 * @method Tip       getTip()           Returns the current record's "Tip" value
 * @method UsedTip   setId()            Sets the current record's "id" value
 * @method UsedTip   setTaskStateId()   Sets the current record's "task_state_id" value
 * @method UsedTip   setTipId()         Sets the current record's "tip_id" value
 * @method UsedTip   setStatus()        Sets the current record's "status" value
 * @method UsedTip   setUsedSince()     Sets the current record's "used_since" value
 * @method UsedTip   setTaskState()     Sets the current record's "TaskState" value
 * @method UsedTip   setTip()           Sets the current record's "Tip" value
 * 
 * @package    sf
 * @subpackage model
 * @author     VozdvIN
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseUsedTip extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('used_tips');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('task_state_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('tip_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('status', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => 0,
             ));
        $this->hasColumn('used_since', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));


        $this->index('ui_state_tip', array(
             'type' => 'unique',
             'fields' => 
             array(
              0 => 'task_state_id',
              1 => 'tip_id',
             ),
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('TaskState', array(
             'local' => 'task_state_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Tip', array(
             'local' => 'tip_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}