<?php

/**
 * BaseComment
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $post_id
 * @property integer $web_user_id
 * @property clob $text
 * @property integer $create_time
 * @property WebUser $WebUser
 * @property Post $Post
 * 
 * @method integer getId()          Returns the current record's "id" value
 * @method integer getPostId()      Returns the current record's "post_id" value
 * @method integer getWebUserId()   Returns the current record's "web_user_id" value
 * @method clob    getText()        Returns the current record's "text" value
 * @method integer getCreateTime()  Returns the current record's "create_time" value
 * @method WebUser getWebUser()     Returns the current record's "WebUser" value
 * @method Post    getPost()        Returns the current record's "Post" value
 * @method Comment setId()          Sets the current record's "id" value
 * @method Comment setPostId()      Sets the current record's "post_id" value
 * @method Comment setWebUserId()   Sets the current record's "web_user_id" value
 * @method Comment setText()        Sets the current record's "text" value
 * @method Comment setCreateTime()  Sets the current record's "create_time" value
 * @method Comment setWebUser()     Sets the current record's "WebUser" value
 * @method Comment setPost()        Sets the current record's "Post" value
 * 
 * @package    sf
 * @subpackage model
 * @author     VozdvIN
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseComment extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('comments');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('post_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('web_user_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('text', 'clob', null, array(
             'type' => 'clob',
             'notnull' => true,
             ));
        $this->hasColumn('create_time', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('WebUser', array(
             'local' => 'web_user_id',
             'foreign' => 'id',
             'onDelete' => 'SET NULL'));

        $this->hasOne('Post', array(
             'local' => 'post_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}