<?php

/**
 * BasePermission
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $description
 * @property Doctrine_Collection $GrantedPermission
 * 
 * @method integer             getId()                Returns the current record's "id" value
 * @method string              getDescription()       Returns the current record's "description" value
 * @method Doctrine_Collection getGrantedPermission() Returns the current record's "GrantedPermission" collection
 * @method Permission          setId()                Sets the current record's "id" value
 * @method Permission          setDescription()       Sets the current record's "description" value
 * @method Permission          setGrantedPermission() Sets the current record's "GrantedPermission" collection
 * 
 * @package    sf
 * @subpackage model
 * @author     VozdvIN
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePermission extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('permissions');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('description', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('GrantedPermission', array(
             'local' => 'id',
             'foreign' => 'permission_id'));
    }
}