<?php

/**
 * BaseRegion
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property Doctrine_Collection $games
 * @property Doctrine_Collection $teams
 * @property Doctrine_Collection $webUsers
 * 
 * @method integer             getId()       Returns the current record's "id" value
 * @method string              getName()     Returns the current record's "name" value
 * @method Doctrine_Collection getGames()    Returns the current record's "games" collection
 * @method Doctrine_Collection getTeams()    Returns the current record's "teams" collection
 * @method Doctrine_Collection getWebUsers() Returns the current record's "webUsers" collection
 * @method Region              setId()       Sets the current record's "id" value
 * @method Region              setName()     Sets the current record's "name" value
 * @method Region              setGames()    Sets the current record's "games" collection
 * @method Region              setTeams()    Sets the current record's "teams" collection
 * @method Region              setWebUsers() Sets the current record's "webUsers" collection
 * 
 * @package    sf
 * @subpackage model
 * @author     VozdvIN
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseRegion extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('regions');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('name', 'string', 32, array(
             'type' => 'string',
             'notnull' => true,
             'default' => '(Любой)',
             'length' => 32,
             ));


        $this->index('ui_state_value', array(
             'type' => 'unique',
             'fields' => 
             array(
              0 => 'id',
              1 => 'name',
             ),
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Game as games', array(
             'local' => 'id',
             'foreign' => 'region_id'));

        $this->hasMany('Team as teams', array(
             'local' => 'id',
             'foreign' => 'region_id'));

        $this->hasMany('WebUser as webUsers', array(
             'local' => 'id',
             'foreign' => 'region_id'));
    }
}