<?php

/**
 * Answer
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    sf
 * @subpackage model
 * @author     VozdvIN
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Answer extends BaseAnswer implements IStored
{

  //// IStored ////

  public static function all()
  {
    return Utils::all('Answer');
  }

  public static function byId($id)
  {
    return Utils::byId('Answer', $id);
  }

  //// Self ////

  /**
   * Устанаваливает значения по умолчанию для тех полей, которые не заполнены.
   */
  protected function initDefaults()
  {
    //reserved
  }

}