<?php

/**
 * Blog
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    sf
 * @subpackage model
 * @author     VozdvIN
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Blog extends BaseBlog
{
  const POSTS_PER_PAGE = 5;
 
  /**
   * Возвращает номер максимально возможной страницы с сообщениями
   */
  public function getMaxPostsPage()
  {
    return round(($this->posts->count() / Blog::POSTS_PER_PAGE) + 0.4);
  }
  
  /**
   * Возвращает сообщения на указанной странице
   * 
   * @param   integer   $page   номер страницы
   * 
   * @return  Doctrine_Collection<Post>
   */
  public function getPostsOnPage($page)
  {
    $maxPage = $this->getMaxPostsPage();
    $usePage = ($page > $maxPage) ? $maxPage : $page;

    $usePage = ($usePage < 1) ? 1 : $usePage;

    return Doctrine::getTable('Post')
        ->createQuery('p')->leftJoin('p.WebUser')
        ->select()->where('blog_id = ?', $this->id)->orderBy('create_time DESC')
        ->offset(Blog::POSTS_PER_PAGE * ($usePage - 1))->limit(Blog::POSTS_PER_PAGE)
        ->execute();
  }
}