<?php

/**
 * GameCreateRequestTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class GameCreateRequestTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object GameCreateRequestTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('GameCreateRequest');
    }
}