<?php

/**
 * TaskTransitionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TaskTransitionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TaskTransitionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TaskTransition');
    }
}