<?php

/**
 * TeamCreateRequest
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    sf
 * @subpackage model
 * @author     VozdvIN
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class TeamCreateRequest extends BaseTeamCreateRequest implements IStored
{

  //// IStored ////
  
  static function all()
  {
    return Utils::all('TeamCreateRequest');
  }
 
  static function byId($id)
  {
    return Utils::byId('TeamCreateRequest', $id);
  }
  
  //// Public ////
  
  /**
   * Выполняет создание команды по заявке.
   * 
   * @param TeamCreateRequest $teamCreateRequest 
   * 
   * @return Team Созданная команда
   */
  public static function doCreate(TeamCreateRequest $teamCreateRequest)
  {
    $team = new Team;
    $team->name = $teamCreateRequest->name;
    $team->full_name = $teamCreateRequest->full_name;
    $team->save(); //Требуется, так как иначе не удастся включить капитана.
    //Так как команда еще не существует, то в нее можно просто включить
    //автора заявки без всяких проверок.
    $teamPlayer = new TeamPlayer;
    $teamPlayer->team_id = $team->id;
    $teamPlayer->web_user_id = $teamCreateRequest->web_user_id;
    $teamPlayer->is_leader = true;
    $team->teamPlayers->add($teamPlayer);
    $team->save();
    $teamCreateRequest->delete();
    return $team;
  }
  
}