<?php

/**
 * UsedTipTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UsedTipTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object UsedTipTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('UsedTip');
    }
}