editSuccess:
  metas:
    title: "Настройки команды"
  has_layout: true  
  layout:     layout
showSuccess:
  metas:
    title: "Настройки команды"
  has_layout: true  
  layout:     layout

all:
  metas:
    title: "Текущее задание"
  has_layout: true  
  layout:     currentTaskLayout    