<?php

/**
 * GameCreateRequest
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    sf
 * @subpackage model
 * @author     VozdvIN
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class GameCreateRequest extends BaseGameCreateRequest implements IStored
{
  const MAX_REQUESTS_PER_TEAM = 3; // Максимальное число активных заявок от одной команды.
  
  //// IStored ////
  
  static function all()
  {
    return Utils::all('GameCreateRequest');
  }
 
  static function byId($id)
  {
    return Utils::byId('GameCreateRequest', $id);
  }
  
  //// Public ////
  
  /**
   * Создает игру по заявке, заявка удаляется.
   * 
   * @param   GameCreateRequest   $gameCreateRequest  заявка
   * 
   * @return  Game                                    созданная игра
   */
  public static function doCreate(GameCreateRequest $gameCreateRequest)
  {
    $game = new Game;
    $game->name = $gameCreateRequest->name;
    $game->team_id = $gameCreateRequest->team_id;
    $game->initDefaults();
    $game->region_id = $gameCreateRequest->Team->getRegionSafe()->id;
    $game->save();
    
    $gameCreateRequest->delete();
    
    return $game;
  }
  
}