<?php

/**
 * Permission
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    sf
 * @subpackage model
 * @author     VozdvIN
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Permission extends BasePermission implements IStored
{
  //Внимание!! Константы должны идти с 1 по порядку!
  //Внимание!! Поддерживать сихронность с файлом \data\sql\DBInit.sql.

  //Админ
  const ROOT = '1'; //'root';
  //Пользователи
  const WEB_USER_INDEX = '2';
  const WEB_USER_SHOW = '3';
  const WEB_USER_MODER = '4';
  //Права
  const PERMISSION_MODER = '5';
  //Команды
  const TEAM_INDEX = '6';
  const TEAM_SHOW = '7';
  const TEAM_MODER = '8';
  //Игры
  const GAME_INDEX = '9';
  const GAME_SHOW = '10';
  const GAME_ACTOR = '11';
  const GAME_AUTHOR = '12';
  const GAME_MODER = '13';
  //Блоги
  const BLOG_MODER = '14';

  //// IStored ////

  static function all()
  {
    return Utils::all('Permissions');
  }

  static function byId($id)
  {
    return Utils::byId('Permission', $id);
  }

}