<?php

/**
 * PostedAnswerTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PostedAnswerTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PostedAnswerTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PostedAnswer');
    }
}