<?php

/**
 * SystemSettings
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    sf
 * @subpackage model
 * @author     VozdvIN
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class SystemSettings extends BaseSystemSettings
{
  public static function getInstance()
  {
    $res = Doctrine::getTable('SystemSettings')->find(0);
    if ($res)
    {
      return $res;
    }
    else
    {
      //Похоже настройки еще не выполнялись.
      $settings = new SystemSettings();
      $settings->id = 0;
      $settings->save(); //Значения будут назначены самой БД из значений по умолчанию.
      return $settings;
    }
  }  
}