<?php

/**
 * TaskStateTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TaskStateTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TaskStateTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TaskState');
    }
}