<?php

/**
 * TaskConstraintTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TaskConstraintTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TaskConstraintTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TaskConstraint');
    }
}