<?php

/**
 * TeamStateTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TeamStateTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TeamStateTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TeamState');
    }
}