<?php

/**
 * TeamCreateRequest
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    sf
 * @subpackage model
 * @author     VozdvIN
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class TeamCreateRequest extends BaseTeamCreateRequest implements IStored
{

  //// IStored ////
  
  static function all()
  {
    return Utils::all('TeamCreateRequest');
  }
 
  static function byId($id)
  {
    return Utils::byId('TeamCreateRequest', $id);
  }
  
  //// Public ////
  
  /**
   * Возвращает список заявок от указанного пользователя.
   * 
   * @param   WebUser   $webUser
   * @return  Doctrine_Collection
   */
  public static function byAuthor(WebUser $webUser)
  {
    $res = Doctrine::getTable('TeamCreateRequest')->findBy('web_user_id', $webUser->id);
    return ($res->count() == 0) ? false : $res;
  }
  
}