<?php

/**
 * Tip
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    sf
 * @subpackage model
 * @author     VozdvIN
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Tip extends BaseTip implements IStored
{

  //// IStored ////

  public static function all()
  {
    return Utils::all('Tip');
  }

  public static function byId($id)
  {
    return Utils::byId('Tip', $id);
  }

  //// Special ////

  /**
   * Устанаваливает значения по умолчанию для тех полей, которые не заполнены.
   */
  public function initDefaults()
  {
    if ($this->delay <= 0)
    {
      $this->delay = $this->Task->tips->count() * $this->Task->Game->time_per_tip;
    }
  }

}