<?php

/**
 * TipTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TipTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TipTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Tip');
    }
}