<?php

/**
 * UsedTip
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    sf
 * @subpackage model
 * @author     VozdvIN
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class UsedTip extends BaseUsedTip
{
  const TIP_WAIT = 0;   //Ожидает использования
  const TIP_USED = 900; //Использована

}