# Ответ
Answer:
  tableName: answers
  columns:
    id: { type: integer, primary: true, notnull: true, autoincrement: true }
    # Задание
    task_id: { type: integer, notnull: true }
    # Название (отображается только организаторам)
    name: { type: string(64), notnull: true }
    # Описание типа (отображается игрокам)
    info: { type: string(32), notnull: true }
    # Значение (вводится игроками для зачета)
    value: { type: string(32), notnull: true }
  relations:
    Task:
      foreignAlias: answers
    # При удалении задания удаляются все его ответы
      onDelete: CASCADE
  indexes:
    # Ответы не могут повторяться в рамках задания
    ui_task_value:
      type: unique
      fields:
        - task_id
        - value
