# Сообщение в блог
Post:
  tableName: posts
  columns:
    id: { type: integer, primary: true, notnull: true, autoincrement: true }
    # Блог-владелец
    blog_id: { type: integer, notnull: true }
    # Автор сообщения
    web_user_id: { type: integer }
    # Сообщение
    text: { type: clob, notnull: true }
    # Дата создания, время Unix
    create_time: { type: integer }
  relations:
    WebUser:
      foreignAlias: posts
    # При удалении пользователя все его сообщения сохраняются
      onDelete: SET NULL
    Blog:
      foreignAlias: posts
    # При удалении блога все его сообщения удаляются
      onDelete: CASCADE
