# Регион
Region:
  tableName: regions
  columns:
    id: { type: integer, notnull: true, primary: true, autoincrement: true }
    # Название
    name: { type: string(32), notnull: true, default: '(Любой)' } 
    # Пользователи из данного региона
    #webUsers: Doctrine_Collection<WebUser>
    # Команды из данного региона
    #teams: Doctrine_Collection<Team>
    # Игры в данном регионе
    #games: Doctrine_Collection<Game>
  indexes:
    # Каждый регион уникален
    ui_state_value:
      type: unique
      fields:
        - id
        - name