# Пользователь системы
WebUser:
  tableName: web_users
  columns:
    id: { type: integer, notnull: true, primary: true, autoincrement: true }
    # Логин
    login: { type: string(32), notnull: true }
    # Хэш пароля
    pwd_hash: { type: string(32), notnull: true }
    # Полное имя пользователя
    full_name: string(255)
    # Адрес электронной почты
    email: { type: string(255), notnull: true }
    # Поле общего назначения
    tag: string(64)
    # Признак активации аккаунта, для блокировки - сбросить
    is_enabled: { type: boolean, notnull: true, default: false }
    # Полученные пользователем разрешения
    #grantedPermissions: Doctrine_Collection<GrantedPermission>
    # Введенные пользователем ответы
    #postedAnswers: Doctrine_Collection<PostedAnswer>