# Сообщение в блог
Comment:
  tableName: comments
  columns:
    id: { type: integer, primary: true, notnull: true, autoincrement: true }
    # Сообщение-владелец
    post_id: { type: integer, notnull: true }
    # Автор комментария
    web_user_id: { type: integer }
    # Комментарий
    text: { type: clob, notnull: true }
    # Дата создания, время Unix
    create_time: { type: integer }    
  relations:
    WebUser:
      foreignAlias: posts
    # При удалении пользователя все его комментарии сохраняются
      onDelete: SET NULL
    Post:
      foreignAlias: comments
    # При удалении сообщения все его комментарии удаляются
      onDelete: CASCADE
