TaskTransition:
# Фильтр перехода между заданиями, одна запись.
# Если фильтры пройдет одно или более заданий с ручным выбором,
# то автовыбор отменяется, игрокам предоставляется выбор.
# Если фильтры не пройдет ни одного задания, то фильтры будут отменены.
# После этого все достуные задания участвуют в выборе.
  tableName: task_transitions
  columns:
    id: { type: integer, primary: true, notnull: true, autoincrement: true }
  # Опорное задание
    task_id: { type: integer, notnull: true }
  # Целевое задание (не всегда актуально, целостность через БД не поддерживается)
    target_task_id: { type: integer, notnull: true, default: 0 }
  # Переход разрешен только если опорное задание выполнено
    allow_on_success: { type: boolean, notnull: true, default: true }
  # Переход разрешен только если опорное задание провалено
    allow_on_fail: { type: boolean, notnull: true, default: true }
  # Игрокам будет предоставлена возможность самим выбрать это вариант
    manual_selection: { type: boolean, notnull: true, default: false }
  relations:
    Task:
      foreignAlias: taskTransitions
      # При удалении задания удаляются все его фильтры перехода
      onDelete: CASCADE
  indexes:
  # Переход с опорного задания на другое должен быть уникален
    ui_task_target_task:
      type: unique
      fields:
        - task_id
        - target_task_id